spring.application.name=EventSplit_1.0
# Adres bazy: localhost, port 5432, nazwa bazy mydatabase
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
# Pokazuj zapytania SQL w konsoli
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080